version: "3.9"
services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
  server:

    build: .
    
    ports:
      - "8080:8080"
    
    depends_on:
      - redis

