version: "3.9"

networks:
  zingping-network:
    driver: bridge

services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - zingping-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:14.5
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - 5434:5432
    networks:
      - zingping-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zingping-api:
    volumes:
      - .:app
    build: .
    image: sid00100/zingping-api:latest
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env.production
    networks:
      - zingping-network
